import "./globals.css";
import { Bakbak_One } from "next/font/google";

const bakbak_one = Bakbak_One({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${bakbak_one.className} bg-background w-screen`}>
        {children}
      </body>
    </html>
  );
}
